---
title: "HW 10"
author: "SDS348 Fall 2019"
date: "2019-11-25"
output: html_document
---



<div id="olga-ostrovskaya-oo3662" class="section level2">
<h2>Olga Ostrovskaya, oo3662</h2>
<hr />
<div id="question-1-2-pts" class="section level3">
<h3>Question 1: (2 pts)</h3>
<div id="the-dataset-faithful-contains-information-about-eruptions-of-the-old-faithful-geyser-in-yellowstone-national-park.-the-first-few-observations-are-listed-below." class="section level5">
<h5>The dataset <code>faithful</code> contains information about eruptions of the Old Faithful geyser in Yellowstone National Park. The first few observations are listed below.</h5>
<pre class="r"><code>library(reticulate)
use_python(&quot;C:/Users/olgao/Anaconda3/python.exe&quot;)

faithful&lt;-faithful
head(faithful)</code></pre>
<pre><code>##   eruptions waiting
## 1     3.600      79
## 2     1.800      54
## 3     3.333      74
## 4     2.283      62
## 5     4.533      85
## 6     2.883      55</code></pre>
</div>
<div id="bring-the-dataset-faithful-over-from-r-and-look-at-it-in-python.-the-rest-of-this-assignment-must-be-completed-in-python-unless-otherwise-noted-what-type-of-object-is-it-what-are-the-minimum-and-maximum-values-of-the-variables-eruptions-and-waiting-put-a-dot-after-the-object-and-hit-tab-look-at-all-those-functions" class="section level5">
<h5>Bring the dataset <code>faithful</code> over from R and look at it in Python. THE REST OF THIS ASSIGNMENT MUST BE COMPLETED IN PYTHON UNLESS OTHERWISE NOTED! What type of object is it? What are the minimum and maximum values of the variables eruptions and waiting? Put a dot after the object and hit tab: Look at all those functions!</h5>
<pre class="python"><code>import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
os.environ[&#39;QT_QPA_PLATFORM_PLUGIN_PATH&#39;] = &#39;C:/Users/olgao/Anaconda3/Library/plugins/platforms&#39;

### 1.

faithful=r.faithful 
#again, this may not work by running the chunk on the servers, but it should still knit.
#to read this into python directly, sidestepping the issue, just uncomment and run the following two lines

#faithful=pd.read_csv(&quot;https://vincentarelbundock.github.io/Rdatasets/csv/datasets/faithful.csv&quot;)

#faithful
min(faithful.eruptions); min(faithful.waiting)</code></pre>
<pre><code>## 1.6
## 43.0</code></pre>
<pre class="python"><code>max(faithful.eruptions); max(faithful.waiting)</code></pre>
<pre><code>## 5.1
## 96.0</code></pre>
<pre class="python"><code>faithful.describe()</code></pre>
<pre><code>##         eruptions     waiting
## count  272.000000  272.000000
## mean     3.487783   70.897059
## std      1.141371   13.594974
## min      1.600000   43.000000
## 25%      2.162750   58.000000
## 50%      4.000000   76.000000
## 75%      4.454250   82.000000
## max      5.100000   96.000000</code></pre>
<pre class="python"><code>type(faithful)</code></pre>
<pre><code>## &lt;class &#39;pandas.core.frame.DataFrame&#39;&gt;</code></pre>
<p><em>The min values for eruptions and waiting: 1.6min and 43min; max: 5.1 and 96 mins. Faithful is a Data Frame.</em></p>
<hr />
</div>
</div>
<div id="question-2-4-pts" class="section level3">
<h3>Question 2: (4 pts)</h3>
<div id="now-import-numpy-and-use-functions-from-it-to-compute-the-mean-median-and-variance-for-each-variable.-finally-compute-the-correlation-between-the-two-variables-using-corrcoef-it-will-return-a-matrix.-you-can-access-individual-variables-in-a-dataframe-using-the-.-operator-e.g.-faithful.eruptions." class="section level5">
<h5>Now, import <code>numpy</code> and use functions from it to compute the mean, median, and variance for each variable. Finally, compute the correlation between the two variables using corrcoef (it will return a matrix). You can access individual variables in a dataframe using the <code>.</code> operator (e.g., <code>faithful.eruptions</code>).</h5>
<pre class="python"><code>### 2.
# the easier way is described in Q1 already.
np.mean(faithful.eruptions)</code></pre>
<pre><code>## 3.4877830882352936</code></pre>
<pre class="python"><code>np.var(faithful.eruptions)</code></pre>
<pre><code>## 1.2979388904492855</code></pre>
<pre class="python"><code>np.median(faithful.eruptions)</code></pre>
<pre><code>## 4.0</code></pre>
<pre class="python"><code>np.mean(faithful.waiting)</code></pre>
<pre><code>## 70.8970588235294</code></pre>
<pre class="python"><code>np.var(faithful.waiting)</code></pre>
<pre><code>## 184.14381487889264</code></pre>
<pre class="python"><code>np.median(faithful.waiting)</code></pre>
<pre><code>## 76.0</code></pre>
<pre class="python"><code>np.corrcoef(faithful, rowvar = False)
</code></pre>
<pre><code>## array([[1.        , 0.90081117],
##        [0.90081117, 1.        ]])</code></pre>
<p><em>The mean and variance for eruptions is 3.488 min and 1.298 min. For waiting - 70.9 and 184.1 min. The correlation between eruptions and waiting is very good: 0.901.</em></p>
<hr />
</div>
</div>
<div id="question-3-6-pts" class="section level3">
<h3>Question 3: (6 pts)</h3>
<div id="recall-how-logical-indexing-of-a-dataframe-works-in-python.-to-refresh-your-memory-in-the-example-code-below-i-ask-python-for-the-number-of-rows-in-the-dataset-where-the-variable-waiting-takes-on-values-greater-than-60.-then-i-ask-for-the-average-of-the-variable-eruptions-when-the-variable-waiting-is-above-60." class="section level5">
<h5>Recall how logical indexing of a dataframe works in python. To refresh your memory, in the example code below I ask python for the number of rows in the dataset where the variable <code>waiting</code> takes on values greater than 60. Then I ask for the average of the variable <code>eruptions</code> when the variable <code>waiting</code> is above 60.</h5>
<pre class="python"><code>faithful[faithful.waiting&gt;60].shape</code></pre>
<pre><code>## (189, 2)</code></pre>
<pre class="python"><code>faithful[faithful.waiting&gt;60].eruptions.mean()
# or np.mean(faithful[faithful.waiting&gt;60].eruptions)</code></pre>
<pre><code>## 4.138587301587303</code></pre>
</div>
<div id="pt-what-is-the-standard-deviation-of-the-variable-eruptions" class="section level5">
<h5>3.2 (1 pt) What is the standard deviation of the variable <code>eruptions</code>?</h5>
<pre class="python"><code>### Q3.2.
faithful.eruptions.std()</code></pre>
<pre><code>## 1.1413712511052077</code></pre>
<pre class="python"><code>np.std(faithful.eruptions)</code></pre>
<pre><code>## 1.1392712102257678</code></pre>
<p><em>Q: Why 2 numbers are different?</em>
<em>The SD for the ‘eruptions’ is 1.14 min.</em></p>
</div>
<div id="pts-what-is-the-standard-deviation-of-the-variable-eruptions-when-waiting-is-less-than-the-median" class="section level5">
<h5>3.3 (2 pts) What is the standard deviation of the variable <code>eruptions</code> when <code>waiting</code> is <em>less than</em> the median?</h5>
<pre class="python"><code># Q - I thought it&#39;s python, not R. Is it ok?

### 3.3.
from statistics import median 

#np.median(faithful.waiting)
faithful[faithful.waiting&lt;median(faithful.waiting)].eruptions.std()</code></pre>
<pre><code>## 0.9583443399236853</code></pre>
<pre class="python"><code>np.std(faithful[faithful.waiting&lt;np.median(faithful.waiting)].eruptions)</code></pre>
<pre><code>## 0.9547617317201806</code></pre>
<p><em>Depending on the package, the SD of this subset is 0.95 or 0.96 min.</em></p>
</div>
<div id="pts-what-is-the-standard-deviation-of-the-variable-eruptions-when-waiting-is-greater-than-the-median" class="section level5">
<h5>3.4 (2 pts) What is the standard deviation of the variable <code>eruptions</code> when <code>waiting</code> is <em>greater than</em> the median?</h5>
<pre class="r"><code>### 3.4
library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>faithful %&gt;% filter(waiting &gt; median(waiting)) %&gt;% summarize(m1 = mean(eruptions), sd1 = sd(eruptions))</code></pre>
<pre><code>##         m1       sd1
## 1 4.358364 0.3730518</code></pre>
<p><em>SD of eruptions in this subset is 0.373 min.</em></p>
<hr />
</div>
</div>
<div id="question-4-4-pts" class="section level3">
<h3>Question 4: (4 pts)</h3>
<div id="both-variables-are-measured-in-minutes.-create-two-new-variables-named-eruptions_h-and-waiting_h-that-give-each-variable-in-hours-rather-than-minutes-and-add-them-to-the-dataset-faithful.-to-help-get-you-started-i-have-given-you-code-that-creates-a-new-variable-called-eruptions_minus_one.-instead-computes-the-requested-transformation.-print-out-the-first-few-rows-of-the-updated-dataset-using-head." class="section level5">
<h5>Both variables are measured in minutes. Create two new variables named <code>eruptions_h</code> and <code>waiting_h</code> that give each variable <strong>in hours rather than minutes</strong> and add them to the dataset <code>faithful</code>. To help get you started, I have given you code that creates a new variable called eruptions_minus_one. Instead, computes the requested transformation. Print out the first few rows of the updated dataset using <code>head()</code>.</h5>
<pre class="python"><code>### 4.

# update the code below
#faithful[&#39;eruptions_minus_one&#39;]=(faithful[&#39;eruptions&#39;]-1)
#faithful
#del faithful[&#39;eruptions_minus_one&#39;]

faithful[&#39;eruptions_h&#39;]=(faithful[&#39;eruptions&#39;]/60)
faithful[&#39;waiting_h&#39;]=(faithful[&#39;waiting&#39;]/60)
faithful.head()
</code></pre>
<pre><code>##    eruptions  waiting  eruptions_h  waiting_h
## 0      3.600     79.0      0.06000   1.316667
## 1      1.800     54.0      0.03000   0.900000
## 2      3.333     74.0      0.05555   1.233333
## 3      2.283     62.0      0.03805   1.033333
## 4      4.533     85.0      0.07555   1.416667</code></pre>
</div>
</div>
<div id="question-5-4-pts" class="section level3">
<h3>Question 5: (4 pts)</h3>
<div id="lets-make-some-plots-in-python" class="section level5">
<h5>Let’s make some plots in python!</h5>
</div>
<div id="pt-create-a-boxplot-of-each-original-variable-eruptions-and-waiting-using-the-boxplot-function-from-matplotlib" class="section level5">
<h5>5.1 (1 pt) Create a boxplot of each original variable (eruptions and waiting) using the <code>boxplot()</code> function from matplotlib</h5>
<pre class="python"><code>### 5.

#plt.boxplot(faithful[&#39;eruptions&#39;])
#plt.boxplot(faithful[&#39;waiting&#39;])
plt.boxplot([faithful[&#39;eruptions&#39;], faithful[&#39;waiting&#39;]])</code></pre>
<pre><code>## {&#39;whiskers&#39;: [&lt;matplotlib.lines.Line2D object at 0x000000002AF91C88&gt;, &lt;matplotlib.lines.Line2D object at 0x000000003B9DA550&gt;, &lt;matplotlib.lines.Line2D object at 0x000000003B9EB978&gt;, &lt;matplotlib.lines.Line2D object at 0x000000003B9EBCC0&gt;], &#39;caps&#39;: [&lt;matplotlib.lines.Line2D object at 0x000000003B9DA898&gt;, &lt;matplotlib.lines.Line2D object at 0x000000003B9DABE0&gt;, &lt;matplotlib.lines.Line2D object at 0x000000003B9EBDA0&gt;, &lt;matplotlib.lines.Line2D object at 0x000000003B9FA390&gt;], &#39;boxes&#39;: [&lt;matplotlib.lines.Line2D object at 0x000000003B9C6E48&gt;, &lt;matplotlib.lines.Line2D object at 0x000000003B9EB5F8&gt;], &#39;medians&#39;: [&lt;matplotlib.lines.Line2D object at 0x000000003B9DAF28&gt;, &lt;matplotlib.lines.Line2D object at 0x000000003B9FA6D8&gt;], &#39;fliers&#39;: [&lt;matplotlib.lines.Line2D object at 0x000000002AF67438&gt;, &lt;matplotlib.lines.Line2D object at 0x000000003B9FAA20&gt;], &#39;means&#39;: []}</code></pre>
<pre class="python"><code>plt.show()
#replace df, variable with your stuff</code></pre>
<p><img src="/HW10_oo3662_files/figure-html/unnamed-chunk-9-1.png" width="768" style="display: block; margin: auto;" /></p>
</div>
<div id="pt-create-a-histogram-of-each-original-variable-using-the-hist-function." class="section level5">
<h5>5.2 (1 pt) Create a histogram of each original variable using the <code>hist()</code> function.</h5>
<pre class="python"><code>### 5.2.

plt.hist(faithful[&#39;eruptions&#39;])</code></pre>
<pre><code>## (array([45., 36., 13.,  3.,  4., 12., 29., 52., 54., 24.]), array([1.6 , 1.95, 2.3 , 2.65, 3.  , 3.35, 3.7 , 4.05, 4.4 , 4.75, 5.1 ]), &lt;a list of 10 Patch objects&gt;)</code></pre>
<pre class="python"><code>plt.hist(faithful[&#39;waiting&#39;])</code></pre>
<pre><code>## (array([16., 28., 26., 24.,  9., 23., 62., 55., 23.,  6.]), array([43. , 48.3, 53.6, 58.9, 64.2, 69.5, 74.8, 80.1, 85.4, 90.7, 96. ]), &lt;a list of 10 Patch objects&gt;)</code></pre>
<pre class="python"><code>plt.show()</code></pre>
<p><img src="/HW10_oo3662_files/figure-html/unnamed-chunk-10-1.png" width="768" style="display: block; margin: auto;" /></p>
</div>
<div id="pt-create-a-scatterplot-by-plotting-both-variables-against-each-other-using-the-plot-function.-note-that-plot-takes-two-arguments-the-x-axis-variable-and-the-y-axis-variable." class="section level5">
<h5>5.3 (1 pt) Create a scatterplot by plotting both variables against each other using the <code>plot()</code> function. Note that plot takes two arguments: the x-axis variable and the y-axis variable.</h5>
<pre class="python"><code>### 5.3.
plt.scatter(faithful[&quot;eruptions&quot;],faithful[&quot;waiting&quot;])
plt.show()</code></pre>
<p><img src="/HW10_oo3662_files/figure-html/unnamed-chunk-11-1.png" width="768" style="display: block; margin: auto;" /></p>
</div>
<div id="pt-load-the-tips-dataset-from-seaborn-a-plotting-package-we-will-use-later.-have-a-look-at-it-below.-what-type-of-object-is-it" class="section level5">
<h5>6.1 (1 pt) Load the tips dataset from <code>seaborn</code> (a plotting package we will use later). Have a look at it below. What type of object is it?</h5>
<pre class="python"><code>#import pandas as pd
#pd.read_csv(&quot;http://www.justFYIyouCanReadDataFromURLs.com/myfile.csv&quot;)

tips = sns.load_dataset(&#39;tips&#39;)
iris = sns.load_dataset(&#39;iris&#39;) #yep, that iris
type(tips)</code></pre>
<pre><code>## &lt;class &#39;pandas.core.frame.DataFrame&#39;&gt;</code></pre>
<pre class="python"><code>tips.head()</code></pre>
<pre><code>##    total_bill   tip     sex smoker  day    time  size
## 0       16.99  1.01  Female     No  Sun  Dinner     2
## 1       10.34  1.66    Male     No  Sun  Dinner     3
## 2       21.01  3.50    Male     No  Sun  Dinner     3
## 3       23.68  3.31    Male     No  Sun  Dinner     2
## 4       24.59  3.61  Female     No  Sun  Dinner     4</code></pre>
<pre class="python"><code>tips.describe()

#using pandas groupby functionality</code></pre>
<pre><code>##        total_bill         tip        size
## count  244.000000  244.000000  244.000000
## mean    19.785943    2.998279    2.569672
## std      8.902412    1.383638    0.951100
## min      3.070000    1.000000    1.000000
## 25%     13.347500    2.000000    2.000000
## 50%     17.795000    2.900000    2.000000
## 75%     24.127500    3.562500    3.000000
## max     50.810000   10.000000    6.000000</code></pre>
<pre class="python"><code>groups = tips.groupby(&#39;sex&#39;)
groups[&#39;tip&#39;].mean()

#tips.to_csv(&quot;tips.csv&quot;) #create tips.csv file in case reticulate isn&#39;t working so you can read it into R</code></pre>
<pre><code>## sex
## Male      3.089618
## Female    2.833448
## Name: tip, dtype: float64</code></pre>
<p><em>Tips is a data frame. The dropped vars are categorical - sex, smoker, date, time.</em></p>
</div>
<div id="pt-access-tips-using-pydf-in-r-and-make-a-plot-with-ggplot-illustrating-the-relationship-between-total_bill-tip-time-and-sex-find-an-effective-way-to-include-all-four-variables-in-the-same-plot" class="section level5">
<h5>6.2 (1 pt) Access tips using <code>py$df</code> in R and make a plot with ggplot illustrating the relationship between total_bill, tip, time, and sex (find an effective way to include all four variables in the same plot)!</h5>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages ----------------------------------------------------- tidyverse 1.2.1 --</code></pre>
<pre><code>## v ggplot2 3.2.1     v readr   1.3.1
## v tibble  2.1.1     v purrr   0.3.2
## v tidyr   1.0.0     v stringr 1.4.0
## v ggplot2 3.2.1     v forcats 0.4.0</code></pre>
<pre><code>## -- Conflicts -------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>#tips&lt;-read.csv(&quot;tips.csv&quot;)

tips&lt;- py$tips
#View(tips)
tips %&gt;% ggplot(aes(total_bill, tip, color = sex))+
  geom_point(size = 3)+
  facet_wrap(~time)</code></pre>
<p><img src="/HW10_oo3662_files/figure-html/unnamed-chunk-13-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre><code>## R version 3.5.3 (2019-03-11)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 18362)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] forcats_0.4.0   stringr_1.4.0   purrr_0.3.2     readr_1.3.1    
##  [5] tidyr_1.0.0     tibble_2.1.1    ggplot2_3.2.1   tidyverse_1.2.1
##  [9] dplyr_0.8.3     reticulate_1.13 knitr_1.26     
## 
## loaded via a namespace (and not attached):
##  [1] tidyselect_0.2.5 xfun_0.11        haven_2.1.0      lattice_0.20-38 
##  [5] colorspace_1.4-1 vctrs_0.2.0      generics_0.0.2   htmltools_0.3.6 
##  [9] yaml_2.2.0       rlang_0.4.0      pillar_1.3.1     withr_2.1.2     
## [13] glue_1.3.1       modelr_0.1.5     readxl_1.3.1     lifecycle_0.1.0 
## [17] munsell_0.5.0    blogdown_0.17    gtable_0.3.0     cellranger_1.1.0
## [21] rvest_0.3.4      evaluate_0.14    labeling_0.3     broom_0.5.2     
## [25] Rcpp_1.0.1       backports_1.1.4  scales_1.0.0     jsonlite_1.6    
## [29] hms_0.4.2        png_0.1-7        digest_0.6.18    stringi_1.4.3   
## [33] bookdown_0.16    grid_3.5.3       cli_1.1.0        tools_3.5.3     
## [37] magrittr_1.5     lazyeval_0.2.2   crayon_1.3.4     pkgconfig_2.0.2 
## [41] zeallot_0.1.0    Matrix_1.2-15    xml2_1.2.2       lubridate_1.7.4 
## [45] assertthat_0.2.1 rmarkdown_1.18   httr_1.4.1       rstudioapi_0.10 
## [49] R6_2.4.0         nlme_3.1-137     compiler_3.5.3</code></pre>
<pre><code>## [1] &quot;2019-12-11 23:32:31 CST&quot;</code></pre>
<pre><code>##        sysname        release        version       nodename        machine 
##      &quot;Windows&quot;       &quot;10 x64&quot;  &quot;build 18362&quot;      &quot;OLECHKA&quot;       &quot;x86-64&quot; 
##          login           user effective_user 
##        &quot;olgao&quot;        &quot;olgao&quot;        &quot;olgao&quot;</code></pre>
</div>
</div>
</div>
