---
title: "HW 10"
author: "SDS348 Fall 2019"
date: "2019-11-25"
output: html_document
---

```{r global_options, include=FALSE}
library(knitr)
opts_chunk$set(fig.align="center", fig.height=5, fig.width=8)
```

## Olga Ostrovskaya, oo3662

---

### Question 1: (2 pts)

##### The dataset `faithful` contains information about eruptions of the Old Faithful geyser in Yellowstone National Park. The first few observations are listed below.

```{R}
library(reticulate)
use_python("C:/Users/olgao/Anaconda3/python.exe")

faithful<-faithful
head(faithful)
```

##### Bring the dataset `faithful` over from R and look at it in Python. THE REST OF THIS ASSIGNMENT MUST BE COMPLETED IN PYTHON UNLESS OTHERWISE NOTED! What type of object is it? What are the minimum and maximum values of the variables eruptions and waiting? Put a dot after the object and hit tab: Look at all those functions!

```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/olgao/Anaconda3/Library/plugins/platforms'

### 1.

faithful=r.faithful 
#again, this may not work by running the chunk on the servers, but it should still knit.
#to read this into python directly, sidestepping the issue, just uncomment and run the following two lines

#faithful=pd.read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/datasets/faithful.csv")

#faithful
min(faithful.eruptions); min(faithful.waiting)
max(faithful.eruptions); max(faithful.waiting)
faithful.describe()
type(faithful)

```

*The min values for eruptions and waiting: 1.6min and 43min; max: 5.1 and 96 mins. Faithful is a Data Frame.* 

---

### Question 2: (4 pts)

##### Now, import `numpy` and use functions from it to compute the mean, median, and variance for each variable. Finally, compute the correlation between the two variables using corrcoef (it will return a matrix). You can access individual variables in a dataframe using the `.` operator (e.g., `faithful.eruptions`).

```{python}
### 2.
# the easier way is described in Q1 already.
np.mean(faithful.eruptions)
np.var(faithful.eruptions)
np.median(faithful.eruptions)

np.mean(faithful.waiting)
np.var(faithful.waiting)
np.median(faithful.waiting)

np.corrcoef(faithful, rowvar = False)


```

*The mean and variance for eruptions is 3.488 min and 1.298 min. For waiting - 70.9 and 184.1 min. The correlation between eruptions and waiting is very good: 0.901.*

---

### Question 3: (6 pts)

##### Recall how logical indexing of a dataframe works in python. To refresh your memory, in the example code below I ask python for the number of rows in the dataset where the variable `waiting` takes on values greater than 60. Then I ask for the average of the variable `eruptions` when the variable `waiting` is above 60.

```{python}
faithful[faithful.waiting>60].shape
faithful[faithful.waiting>60].eruptions.mean()
# or np.mean(faithful[faithful.waiting>60].eruptions)
```

##### 3.2 (1 pt) What is the standard deviation of the variable `eruptions`?

```{python}
### Q3.2.
faithful.eruptions.std()
np.std(faithful.eruptions)

```

*Q: Why 2 numbers are different?*
*The SD for the 'eruptions' is 1.14 min.*

##### 3.3 (2 pts) What is the standard deviation of the variable `eruptions` when `waiting` is *less than* the median? 

```{python}
# Q - I thought it's python, not R. Is it ok?

### 3.3.
from statistics import median 

#np.median(faithful.waiting)
faithful[faithful.waiting<median(faithful.waiting)].eruptions.std()
np.std(faithful[faithful.waiting<np.median(faithful.waiting)].eruptions)

```

*Depending on the package, the SD of this subset is 0.95 or 0.96 min.*

##### 3.4 (2 pts) What is the standard deviation of the variable `eruptions` when `waiting` is *greater than* the median?

```{R}
### 3.4
library(dplyr)
faithful %>% filter(waiting > median(waiting)) %>% summarize(m1 = mean(eruptions), sd1 = sd(eruptions))

```

*SD of eruptions in this subset is 0.373 min.*

---

### Question 4: (4 pts)

##### Both variables are measured in minutes. Create two new variables named `eruptions_h` and `waiting_h` that give each variable **in hours rather than minutes** and add them to the dataset `faithful`. To help get you started, I have given you code that creates a new variable called eruptions_minus_one. Instead, computes the requested transformation. Print out the first few rows of the updated dataset using `head()`.


```{python}
### 4.

# update the code below
#faithful['eruptions_minus_one']=(faithful['eruptions']-1)
#faithful
#del faithful['eruptions_minus_one']

faithful['eruptions_h']=(faithful['eruptions']/60)
faithful['waiting_h']=(faithful['waiting']/60)
faithful.head()


```


### Question 5: (4 pts)

##### Let's make some plots in python!

##### 5.1 (1 pt) Create a boxplot of each original variable (eruptions and waiting) using the `boxplot()` function from matplotlib

```{python}
### 5.

#plt.boxplot(faithful['eruptions'])
#plt.boxplot(faithful['waiting'])
plt.boxplot([faithful['eruptions'], faithful['waiting']])
plt.show()
#replace df, variable with your stuff
```

##### 5.2 (1 pt) Create a histogram of each original variable using the `hist()` function. 

```{python}
### 5.2.

plt.hist(faithful['eruptions'])
plt.hist(faithful['waiting'])
plt.show()
```

##### 5.3 (1 pt) Create a scatterplot by plotting both variables against each other using the `plot()` function. Note that plot takes two arguments: the x-axis variable and the y-axis variable. 

```{python}
### 5.3.
plt.scatter(faithful["eruptions"],faithful["waiting"])
plt.show()
```

##### 6.1 (1 pt) Load the tips dataset from `seaborn` (a plotting package we will use later). Have a look at it below. What type of object is it?  

```{python}
#import pandas as pd
#pd.read_csv("http://www.justFYIyouCanReadDataFromURLs.com/myfile.csv")

tips = sns.load_dataset('tips')
iris = sns.load_dataset('iris') #yep, that iris
type(tips)
tips.head()
tips.describe()

#using pandas groupby functionality
groups = tips.groupby('sex')
groups['tip'].mean()

#tips.to_csv("tips.csv") #create tips.csv file in case reticulate isn't working so you can read it into R
```

*Tips is a data frame. The dropped vars are categorical - sex, smoker, date, time.*

##### 6.2 (1 pt) Access tips using `py$df` in R and make a plot with ggplot illustrating the relationship between total_bill, tip, time, and sex (find an effective way to include all four variables in the same plot)!

```{R}
library(tidyverse)
#tips<-read.csv("tips.csv")

tips<- py$tips
#View(tips)
tips %>% ggplot(aes(total_bill, tip, color = sex))+
  geom_point(size = 3)+
  facet_wrap(~time)

```


```{R, echo=F}
## DO NOT DELETE THIS BLOCK!
sessionInfo()
Sys.time()
Sys.info()
```